// Supported-devices table, mirrored from the landing page.
//
// AUTO-GENERATED — do not edit by hand. Source of truth:
//   openmouse-landing-page/src/supported-mice.ts
// (the table behind openmouse.app/supported, re-checked against the
// @openmouse/protocol driver registry every time the landing page builds).
//
// Regenerate with:
//   node scripts/sync-supported-devices.mjs

export type SupportedDevicesStatus =
  | "supported"
  | "pr"
  | "quickwin"
  | "likely"
  | "driver"
  | "unknown"
  | "bridge"
  | "pending";

export interface SupportedDeviceEntry {
  brand: string;
  model: string;
  status: SupportedDevicesStatus;
  /** Known product ids from the page table (hex), when the driver pins them. */
  pids?: readonly number[];
}

export const SUPPORTED_DEVICES: readonly SupportedDeviceEntry[] = [
  { brand: "Logitech", model: "G502 (all variants)", status: "supported", pids: [0xc07d, 0xc08b] },
  { brand: "Logitech", model: "G203 LIGHTSYNC", status: "supported", pids: [0xc092] },
  { brand: "Logitech", model: "G203 PRODIGY", status: "supported", pids: [0xc084] },
  { brand: "Logitech", model: "G102 LIGHTSYNC", status: "supported", pids: [0xc089] },
  { brand: "Logitech", model: "G402 Hyperion Fury", status: "supported", pids: [0xc07e] },
  { brand: "Logitech", model: "G303 Daedalus Apex", status: "supported", pids: [0xc080] },
  { brand: "Logitech", model: "G303 Shroud Edition", status: "supported" },
  { brand: "Logitech", model: "G Pro (2017)", status: "supported", pids: [0xc085] },
  { brand: "Logitech", model: "G502 HERO (wired)", status: "supported", pids: [0xc08b] },
  { brand: "Logitech", model: "G Pro Hero", status: "supported", pids: [0xc08c] },
  { brand: "Logitech", model: "G903 HERO (wired)", status: "supported", pids: [0xc08e] },
  { brand: "Logitech", model: "G903 Lightspeed", status: "supported" },
  { brand: "Logitech", model: "G403 HERO (wired)", status: "supported", pids: [0xc08f] },
  { brand: "Logitech", model: "G703 (wired)", status: "supported" },
  { brand: "Logitech", model: "G703 Lightspeed", status: "supported" },
  { brand: "Logitech", model: "G Pro X Superlight", status: "supported", pids: [0xc094] },
  { brand: "Logitech", model: "PRO X SUPERLIGHT 2", status: "supported", pids: [0xc09b] },
  { brand: "Logitech", model: "PRO X SUPERLIGHT 2 SE", status: "supported" },
  { brand: "Logitech", model: "PRO X SUPERLIGHT 2 DEX", status: "supported", pids: [0xc0a0] },
  { brand: "Logitech", model: "G305", status: "supported" },
  { brand: "Logitech", model: "MX Master 3S", status: "supported", pids: [0xc548] },
  { brand: "Logitech", model: "G502 X (wired)", status: "supported", pids: [0xc099] },
  { brand: "Logitech", model: "G502 X PLUS (wireless)", status: "supported", pids: [0xc095] },
  { brand: "Logitech", model: "G502 X LIGHTSPEED", status: "supported", pids: [0xc098] },
  { brand: "Logitech", model: "MX Vertical", status: "driver" },
  { brand: "Logitech", model: "MX Master 4", status: "supported" },
  { brand: "Logitech", model: "MX Master 4S", status: "likely" },
  { brand: "Logitech", model: "G304", status: "supported" },
  { brand: "Logitech", model: "G Pro Wireless", status: "supported" },
  { brand: "Logitech", model: "G300s", status: "driver" },
  { brand: "Logitech", model: "G600", status: "driver" },
  { brand: "Logitech", model: "G604 LIGHTSPEED", status: "supported" },
  { brand: "Logitech", model: "G Pro 2 Lightspeed", status: "supported", pids: [0xc09a] },
  { brand: "Logitech", model: "G502 Lightspeed", status: "supported" },
  { brand: "Logitech", model: "MX Master 2S", status: "driver" },
  { brand: "Logitech", model: "MX Anywhere 3", status: "supported", pids: [0xc548] },
  { brand: "Logitech", model: "MX Anywhere 3S", status: "supported", pids: [0xc548] },
  { brand: "Logitech", model: "G309 Lightspeed", status: "supported" },
  { brand: "Logitech", model: "MX Ergo S", status: "supported", pids: [0xc548] },
  { brand: "Logitech", model: "MX Anywhere 2", status: "driver" },
  { brand: "Logitech", model: "Compact Wireless", status: "unknown" },
  { brand: "Logitech", model: "G700s", status: "driver" },
  { brand: "Logitech", model: "M171 Wireless", status: "driver" },
  { brand: "Roccat", model: "Kone Pro Air", status: "driver" },
  { brand: "Roccat", model: "Kone XP Air", status: "driver" },
  { brand: "Roccat", model: "Tyon", status: "driver" },
  { brand: "Roccat", model: "Nyth", status: "driver" },
  { brand: "Roccat", model: "Kain 100 AIMO", status: "driver" },
  { brand: "Roccat", model: "Kone Pro", status: "driver" },
  { brand: "Redragon", model: "M725 Honeycomb", status: "driver" },
  { brand: "Redragon", model: "Impact Elite M913", status: "driver" },
  { brand: "Redragon", model: "PREDATOR M612", status: "driver" },
  { brand: "Redragon", model: "K1ng M916 Pro 4K", status: "driver" },
  { brand: "Redragon", model: "M711 Cobra", status: "driver" },
  { brand: "Redragon", model: "M917 Pro", status: "driver" },
  { brand: "Redragon", model: "M991", status: "driver" },
  { brand: "Redragon", model: "M703", status: "driver" },
  { brand: "Redragon", model: "TAIPAN PRO M810", status: "driver" },
  { brand: "Redragon", model: "Ranger Lite", status: "driver" },
  { brand: "Redragon", model: "Infernal Dragon", status: "driver" },
  { brand: "Redragon", model: "M696 Pro", status: "driver" },
  { brand: "Redragon", model: "M721 Pro", status: "driver" },
  { brand: "Redragon", model: "M724 K1NG 1K", status: "supported", pids: [0xfc7a] },
  { brand: "Ryunix", model: "KYU Pro MX1", status: "supported", pids: [0x26e, 0x26f] },
  { brand: "Delux", model: "M800 Mini", status: "supported", pids: [0xfa60, 0xfa55] },
  { brand: "Dareu", model: "A950 PRO Mg", status: "supported", pids: [0x1114, 0x1117] },
  { brand: "Attack Shark", model: "X3", status: "bridge" },
  { brand: "Attack Shark", model: "X11", status: "bridge" },
  { brand: "Attack Shark", model: "R5 Ultra", status: "supported", pids: [0x46, 0x47] },
  { brand: "Attack Shark", model: "X6", status: "bridge" },
  { brand: "Attack Shark", model: "R3", status: "likely", pids: [0x402d, 0x4026] },
  { brand: "Attack Shark", model: "R1", status: "bridge" },
  { brand: "Attack Shark", model: "X8 Ultra", status: "bridge" },
  { brand: "Attack Shark", model: "X8 SE", status: "bridge" },
  { brand: "Attack Shark", model: "X1", status: "bridge" },
  { brand: "Attack Shark", model: "V3 Pro", status: "bridge" },
  { brand: "Attack Shark", model: "X3 Pro", status: "bridge" },
  { brand: "Attack Shark", model: "X11 SE", status: "bridge" },
  { brand: "Attack Shark", model: "X8 PLUS", status: "bridge" },
  { brand: "Attack Shark", model: "X12", status: "bridge" },
  { brand: "Attack Shark", model: "R6", status: "bridge" },
  { brand: "Attack Shark", model: "G3", status: "bridge" },
  { brand: "Attack Shark", model: "R2", status: "supported", pids: [0x402d, 0x4026] },
  { brand: "Lingbao", model: "M5 Pro", status: "supported", pids: [0x402d, 0x4026] },
  { brand: "Razer", model: "DeathAdder V3 (wired)", status: "supported" },
  { brand: "Razer", model: "DeathAdder V2 (wired)", status: "supported", pids: [0x84] },
  { brand: "Razer", model: "DeathAdder V2 Pro", status: "supported", pids: [0x7c, 0x7d] },
  { brand: "Razer", model: "Cobra", status: "supported", pids: [0xa3] },
  { brand: "Razer", model: "Viper V3 Pro", status: "supported", pids: [0xc0, 0xc1] },
  { brand: "Razer", model: "Viper V2 Pro", status: "supported", pids: [0xa5, 0xa6] },
  { brand: "Razer", model: "Viper V2 Pro (HyperPolling 8000 Hz)", status: "likely", pids: [0xb3] },
  { brand: "Razer", model: "DeathAdder Essential", status: "supported", pids: [0x6e, 0x71, 0x98] },
  { brand: "Razer", model: "Viper Mini", status: "supported", pids: [0x8a] },
  { brand: "Razer", model: "Viper V3 HyperSpeed", status: "supported", pids: [0xb8] },
  { brand: "Razer", model: "Viper V4 Pro", status: "supported", pids: [0xe5, 0xe6] },
  { brand: "Razer", model: "Basilisk V3 (wired)", status: "likely" },
  { brand: "Razer", model: "Basilisk V3 Pro", status: "likely" },
  { brand: "Razer", model: "Viper Ultimate", status: "likely" },
  { brand: "Razer", model: "Basilisk V3 X HyperSpeed", status: "likely", pids: [0xb9] },
  { brand: "Razer", model: "DeathAdder V2 X HyperSpeed", status: "likely" },
  { brand: "Razer", model: "Viper 8KHz", status: "likely" },
  { brand: "Razer", model: "Naga V2 Pro", status: "likely" },
  { brand: "Razer", model: "DeathAdder V3 Pro", status: "supported", pids: [0xb6, 0xb7] },
  { brand: "Razer", model: "DeathAdder V4 Pro", status: "supported", pids: [0xbe, 0xbf] },
  { brand: "Razer", model: "DeathAdder V4 Pro Carbon Fiber Edition", status: "supported", pids: [0xef, 0xf0] },
  { brand: "Razer", model: "Naga Trinity", status: "likely" },
  { brand: "Razer", model: "Naga X", status: "likely" },
  { brand: "Razer", model: "Basilisk Essential", status: "likely" },
  { brand: "Razer", model: "Basilisk", status: "likely" },
  { brand: "Razer", model: "Orochi V2", status: "likely" },
  { brand: "Razer", model: "Cobra Pro", status: "likely", pids: [0xaf, 0xb0] },
  { brand: "Razer", model: "Viper V3 Pro SE", status: "likely", pids: [0xde, 0xdf] },
  { brand: "Razer", model: "Basilisk X HyperSpeed", status: "likely" },
  { brand: "Razer", model: "Naga V2 HyperSpeed", status: "likely" },
  { brand: "Razer", model: "Basilisk Ultimate", status: "likely" },
  { brand: "Razer", model: "DeathAdder Elite", status: "likely", pids: [0x5c] },
  { brand: "Razer", model: "Abyssus 1800", status: "likely", pids: [0x20] },
  { brand: "Razer", model: "Abyssus 2000", status: "likely", pids: [0x5e] },
  { brand: "Razer", model: "Abyssus 2014", status: "likely", pids: [0x42] },
  { brand: "Razer", model: "Abyssus Elite (D.Va Edition)", status: "likely", pids: [0x6a] },
  { brand: "Razer", model: "Abyssus Essential", status: "likely", pids: [0x6b] },
  { brand: "Razer", model: "Abyssus V2", status: "likely", pids: [0x5b] },
  { brand: "Razer", model: "Atheris", status: "likely", pids: [0x62] },
  { brand: "Razer", model: "Basilisk Mobile", status: "likely", pids: [0xd3, 0xd4] },
  { brand: "Razer", model: "Basilisk V2", status: "likely", pids: [0x85] },
  { brand: "Razer", model: "Basilisk V3 35K", status: "likely", pids: [0xcb] },
  { brand: "Razer", model: "Basilisk V3 Pro 35K", status: "likely", pids: [0xcc, 0xcd] },
  { brand: "Razer", model: "Basilisk V3 Pro 35K Phantom Green", status: "likely", pids: [0xd6, 0xd7] },
  { brand: "Razer", model: "DeathAdder 1800", status: "likely", pids: [0x38] },
  { brand: "Razer", model: "DeathAdder 2000", status: "likely", pids: [0x4f] },
  { brand: "Razer", model: "DeathAdder 2013", status: "likely", pids: [0x37] },
  { brand: "Razer", model: "DeathAdder 3500", status: "likely", pids: [0x54] },
  { brand: "Razer", model: "DeathAdder Chroma", status: "likely", pids: [0x43] },
  { brand: "Razer", model: "DeathAdder V2 Lite", status: "likely", pids: [0xa1] },
  { brand: "Razer", model: "DeathAdder V2 Mini", status: "likely", pids: [0x8c] },
  { brand: "Razer", model: "DeathAdder V3 HyperSpeed", status: "likely", pids: [0xc4, 0xc5] },
  { brand: "Razer", model: "Diamondback Chroma", status: "likely", pids: [0x4c] },
  { brand: "Razer", model: "Imperator 2012", status: "likely", pids: [0x2f] },
  { brand: "Razer", model: "Lancehead", status: "likely", pids: [0x59, 0x5a] },
  { brand: "Razer", model: "Lancehead Tournament Edition", status: "likely", pids: [0x60] },
  { brand: "Razer", model: "Lancehead Wireless", status: "likely", pids: [0x6f, 0x70] },
  { brand: "Razer", model: "Mamba", status: "likely", pids: [0x44, 0x45] },
  { brand: "Razer", model: "Mamba 2012", status: "likely", pids: [0x24, 0x25] },
  { brand: "Razer", model: "Mamba Elite", status: "likely", pids: [0x6c] },
  { brand: "Razer", model: "Mamba Tournament Edition", status: "likely", pids: [0x46] },
  { brand: "Razer", model: "Mamba Wireless", status: "likely", pids: [0x72, 0x73] },
  { brand: "Razer", model: "Naga", status: "likely", pids: [0x15] },
  { brand: "Razer", model: "Naga 2012", status: "likely", pids: [0x2e] },
  { brand: "Razer", model: "Naga 2014", status: "likely", pids: [0x40] },
  { brand: "Razer", model: "Naga Chroma", status: "likely", pids: [0x53] },
  { brand: "Razer", model: "Naga Epic", status: "likely", pids: [0x1f] },
  { brand: "Razer", model: "Naga Epic Chroma", status: "likely", pids: [0x3e, 0x3f] },
  { brand: "Razer", model: "Naga Hex", status: "likely", pids: [0x41] },
  { brand: "Razer", model: "Naga Hex (Red)", status: "likely", pids: [0x36] },
  { brand: "Razer", model: "Naga Hex V2", status: "likely", pids: [0x50] },
  { brand: "Razer", model: "Naga Left-Handed Edition 2020", status: "likely", pids: [0x8d] },
  { brand: "Razer", model: "Naga Pro", status: "likely", pids: [0x8f, 0x90] },
  { brand: "Razer", model: "Orochi", status: "likely", pids: [0x48] },
  { brand: "Razer", model: "Orochi 2013", status: "likely", pids: [0x39] },
  { brand: "Razer", model: "Ouroboros 2012", status: "likely", pids: [0x32] },
  { brand: "Razer", model: "Pro Click", status: "likely", pids: [0x77, 0x80] },
  { brand: "Razer", model: "Pro Click Mini", status: "likely", pids: [0x9a] },
  { brand: "Razer", model: "Pro Click V2", status: "likely", pids: [0xd0, 0xd1] },
  { brand: "Razer", model: "Pro Click V2 Vertical Edition", status: "likely", pids: [0xc7, 0xc8] },
  { brand: "Razer", model: "Taipan", status: "likely", pids: [0x34] },
  { brand: "Razer", model: "Viper Mini Signature Edition", status: "likely", pids: [0x9e, 0x9f] },
  { brand: "HyperX", model: "Pulsefire Haste", status: "likely", pids: [0x1727, 0xf8f, 0x48e, 0x28e] },
  { brand: "HyperX", model: "Pulsefire Haste 2", status: "driver" },
  { brand: "HyperX", model: "Pulsefire Haste 2 Wireless", status: "driver" },
  { brand: "HyperX", model: "Pulsefire FPS Pro", status: "driver" },
  { brand: "HyperX", model: "Pulsefire Fuse", status: "driver" },
  { brand: "SteelSeries", model: "Aerox 9 Wireless", status: "supported", pids: [0x185a, 0x1876, 0x1858, 0x1874] },
  { brand: "SteelSeries", model: "Sensei Ten", status: "supported", pids: [0x1832, 0x1834] },
  { brand: "SteelSeries", model: "Aerox 5", status: "supported", pids: [0x1850, 0x1854, 0x185e, 0x1862, 0x1852, 0x185c, 0x1860] },
  { brand: "SteelSeries", model: "Rival 3 Wireless", status: "supported", pids: [0x1830] },
  { brand: "SteelSeries", model: "Rival 3 (wired)", status: "supported", pids: [0x1824, 0x184c] },
  { brand: "SteelSeries", model: "Rival 650 Wireless", status: "supported", pids: [0x172b, 0x1726] },
  { brand: "SteelSeries", model: "Aerox 3", status: "supported", pids: [0x1836] },
  { brand: "SteelSeries", model: "Prime+", status: "supported", pids: [0x182c] },
  { brand: "SteelSeries", model: "Rival 310", status: "supported", pids: [0x1720, 0x171e, 0x1736] },
  { brand: "SteelSeries", model: "Prime Mini Wireless", status: "supported", pids: [0x184a, 0x1848] },
  { brand: "Corsair", model: "NIGHTSWORD RGB", status: "supported", pids: [0x1b5c] },
  { brand: "Corsair", model: "Harpoon RGB Pro", status: "driver" },
  { brand: "Corsair", model: "Katar Pro", status: "driver" },
  { brand: "Corsair", model: "M65 Pro RGB", status: "driver" },
  { brand: "Corsair", model: "Sabre V2 Pro Ultralight", status: "driver" },
  { brand: "Corsair", model: "Scimitar Elite Wireless SE", status: "driver" },
  { brand: "Corsair", model: "M65 RGB Elite", status: "driver" },
  { brand: "Corsair", model: "Scimitar RGB Elite", status: "driver" },
  { brand: "Corsair", model: "Ironclaw RGB", status: "driver" },
  { brand: "Glorious", model: "Model O 2 Pro Wireless", status: "supported", pids: [0x2033] },
  { brand: "Glorious", model: "Model O", status: "supported", pids: [0x2011, 0x2022] },
  { brand: "Glorious", model: "Model D Wireless", status: "supported", pids: [0x2012, 0x2023] },
  { brand: "Glorious", model: "Model D", status: "supported", pids: [0x2012] },
  { brand: "Glorious", model: "Model O2 Pro 4K/8K", status: "likely", pids: [0x201b, 0x2035] },
  { brand: "Glorious", model: "Model O Pro", status: "supported", pids: [0x2015, 0x2027] },
  { brand: "Glorious", model: "Model D2 Pro Wireless 8K", status: "likely", pids: [0x201c, 0x2036] },
  { brand: "Glorious", model: "Model O3 Wireless", status: "likely", pids: [0xa312, 0xa300] },
  { brand: "Endgame Gear", model: "XM2w 4K", status: "supported" },
  { brand: "Endgame Gear", model: "OP1we", status: "supported", pids: [0x1961, 0x1962] },
  { brand: "Endgame Gear", model: "OP1w 4K v2", status: "likely" },
  { brand: "Endgame Gear", model: "OP1 8K", status: "supported", pids: [0x1964, 0x1976, 0x1978] },
  { brand: "Endgame Gear", model: "XM2 8K", status: "supported", pids: [0x1966, 0x1980] },
  { brand: "ATK", model: "F1 V2 Ultra Max", status: "supported" },
  { brand: "ATK", model: "VXE Dragonfly R1 Pro", status: "likely" },
  { brand: "VXE", model: "R1 Pro Max", status: "supported", pids: [0xf58a, 0xf58c] },
  { brand: "VXE", model: "R1 (SE)", status: "likely" },
  { brand: "VXE", model: "R1 SE+", status: "supported", pids: [0xf58e, 0xf58f] },
  { brand: "ATK", model: "X1 V2 Ultimate", status: "likely" },
  { brand: "ATK", model: "A9 Air", status: "likely" },
  { brand: "ATK", model: "F1 Ultimate", status: "likely" },
  { brand: "ATK", model: "F1 Ultimate 2.0", status: "likely" },
  { brand: "ATK", model: "A9 Mini +", status: "likely" },
  { brand: "ATK", model: "VXE Mad R Major", status: "likely" },
  { brand: "ATK", model: "ZERO", status: "supported", pids: [0x1154, 0x1155] },
  { brand: "ATK", model: "VXE Zero Normal", status: "likely" },
  { brand: "VGN", model: "Dragonfly F2 Master+", status: "supported", pids: [0xfb56, 0xfb57] },
  { brand: "WLMouse", model: "Beast X", status: "supported", pids: [0xa883, 0xa884] },
  { brand: "WLMouse", model: "Beast Mini", status: "supported", pids: [0xa885, 0xa886] },
  { brand: "WLMouse", model: "Beast X Pro", status: "supported", pids: [0xa870, 0xa871] },
  { brand: "WLMouse", model: "Sword X", status: "supported", pids: [0xa878, 0xa879] },
  { brand: "WLMouse", model: "Beast Max", status: "supported", pids: [0xa880, 0xa881] },
  { brand: "Pulsar", model: "Tenz Signature", status: "supported" },
  { brand: "Pulsar", model: "X2h", status: "supported" },
  { brand: "Pulsar", model: "X2 V3 ES Mini", status: "supported" },
  { brand: "Pulsar", model: "X3 Medium", status: "supported", pids: [0x3409, 0x3410, 0x5402, 0x5403] },
  { brand: "Pulsar", model: "X2F", status: "supported" },
  { brand: "VAXEE", model: "XE Wireless", status: "supported", pids: [0x1003] },
  { brand: "VAXEE", model: "NP-01S Wireless", status: "supported", pids: [0x1004] },
  { brand: "VAXEE", model: "AX Wireless", status: "supported", pids: [0x1005] },
  { brand: "VAXEE", model: "NP-01 Wireless", status: "supported", pids: [0x1006] },
  { brand: "VAXEE", model: "XE-S Wireless", status: "supported", pids: [0x1007] },
  { brand: "VAXEE", model: "XE-S-L Wireless", status: "supported", pids: [0x1008] },
  { brand: "VAXEE", model: "VAXEE x Ninjutso Sora", status: "supported", pids: [0x1009] },
  { brand: "VAXEE", model: "E1 Wireless", status: "supported", pids: [0x1010] },
  { brand: "VAXEE", model: "NP-01S V2 Wireless", status: "supported", pids: [0x1011] },
  { brand: "VAXEE", model: "XE V2 Wireless", status: "supported", pids: [0x1012] },
  { brand: "VAXEE", model: "NP-01S Ergo Wireless", status: "supported", pids: [0x1013] },
  { brand: "VAXEE", model: "NP-01S V3 Wireless", status: "supported", pids: [0x1014] },
  { brand: "VAXEE", model: "NP-01 Ergo Wireless", status: "supported", pids: [0x1015] },
  { brand: "Lamzu", model: "Maya X", status: "supported", pids: [0x1c, 0x1d, 0x1e] },
  { brand: "Lamzu", model: "Inca", status: "supported", pids: [0x9, 0xf, 0x10] },
  { brand: "Lamzu", model: "Atlantis (shared family ids)", status: "likely", pids: [0xf50f] },
  { brand: "Lamzu", model: "Thorn", status: "quickwin" },
  { brand: "CRDRAKO", model: "KO-ONE", status: "supported", pids: [0x6a, 0x6b] },
  { brand: "Ninjutso", model: "Sora V2", status: "supported", pids: [0xae11, 0xae12, 0xae13, 0xae14, 0xae15, 0xae16] },
  { brand: "Ninjutso", model: "Sora V3", status: "supported", pids: [0xe010] },
  { brand: "Ninjutso", model: "TEN", status: "supported", pids: [0xe020, 0xea01] },
  { brand: "Ninjutso", model: "Sora", status: "likely" },
  { brand: "Teevolution", model: "Terra Pro", status: "supported", pids: [0xf520, 0xf523, 0xf5bb, 0xf522] },
  { brand: "WALLHACK", model: "M-001", status: "supported", pids: [0x1110, 0x807] },
  { brand: "Finalmouse", model: "Starlight-12 / ULX", status: "supported", pids: [0x100] },
  { brand: "Zaunkoenig", model: "M3K", status: "supported", pids: [0xa462] },
  { brand: "Zaunkoenig", model: "M2K", status: "supported", pids: [0xa3cf] },
  { brand: "moddoMOUSE", model: "moddoMOUSE", status: "supported" },
  { brand: "Orbital", model: "Ghost / Pathfinder V2", status: "supported", pids: [0x80c] },
  { brand: "Microsoft", model: "Pro Intellimouse", status: "supported", pids: [0x82a] },
  { brand: "Microsoft", model: "Classic Intellimouse", status: "supported", pids: [0x823] },
  { brand: "Keychron", model: "Nape Pro", status: "supported", pids: [0x440] },
  { brand: "Keychron", model: "M6", status: "supported", pids: [0xd060, 0xd029] },
  { brand: "Asus", model: "Harpe Ace Aim Lab", status: "driver" },
  { brand: "Asus", model: "TUF Gaming M5", status: "driver" },
  { brand: "Asus", model: "Gladius II Core", status: "driver" },
  { brand: "Asus", model: "Strix Impact III", status: "driver" },
  { brand: "Asus", model: "TUF Gaming M3 Gen 1", status: "driver" },
  { brand: "Asus", model: "ROG Gladius II P502", status: "supported", pids: [0x1845] },
  { brand: "Incott", model: "G23 V2 (SE / Pro)", status: "supported", pids: [0x522c, 0x622c] },
  { brand: "Incott", model: "GHERO (and Pro)", status: "likely" },
  { brand: "Incott", model: "G23 (and Pro)", status: "likely" },
  { brand: "Incott", model: "G24 (and Pro)", status: "likely" },
  { brand: "Incott", model: "Zero 29 (and Pro)", status: "likely" },
  { brand: "Incott", model: "Zero 39 (and Pro)", status: "likely" },
  { brand: "RAWM", model: "Blade 1", status: "supported", pids: [0x2328] },
  { brand: "RAWM", model: "ML01", status: "supported", pids: [0x2329] },
  { brand: "RAWM", model: "MH01", status: "supported", pids: [0x232c] },
  { brand: "RAWM", model: "SL01", status: "supported", pids: [0x232d] },
  { brand: "RAWM", model: "SH01", status: "supported", pids: [0x232e, 0x232f] },
  { brand: "RAWM", model: "SH01 Pro", status: "supported", pids: [0x2330, 0x2332] },
  { brand: "RAWM", model: "MH01 Pro", status: "supported", pids: [0x2331] },
  { brand: "RAWM", model: "ES21", status: "supported", pids: [0x2333] },
  { brand: "RAWM", model: "ES21 Pro", status: "supported", pids: [0x2334] },
  { brand: "RAWM", model: "ES21M", status: "supported", pids: [0x2337] },
  { brand: "RAWM", model: "ER21 Pro", status: "supported", pids: [0x2338] },
  { brand: "RAWM", model: "ER21M", status: "supported", pids: [0x2339] },
  { brand: "Bloody", model: "Max W95", status: "driver" },
  { brand: "Fantech", model: "THOR II X16", status: "driver" },
  { brand: "Cooler Master", model: "MasterMouse MM720", status: "driver" },
  { brand: "Cooler Master", model: "MM711", status: "driver" },
  { brand: "K-snake", model: "X11", status: "supported", pids: [0x2255] },
  { brand: "Hitscan", model: "Hyperlight", status: "unknown" },
  { brand: "RAWM", model: "Leviathan V4", status: "unknown" },
  { brand: "AJAZZ", model: "AJ159 Apex", status: "unknown" },
  { brand: "Furycube", model: "G11", status: "unknown" },
  { brand: "Mchose", model: "A7 V2 Ultra+", status: "supported", pids: [0x4021, 0x100b] },
  { brand: "Mchose", model: "MagDock (charging base)", status: "supported", pids: [0x1012] },
  { brand: "Mchose", model: "A7 V2 Ultra", status: "likely" },
  { brand: "Mchose", model: "A7 V2 Pro+", status: "likely" },
  { brand: "Mchose", model: "A7 V2 Pro", status: "likely" },
  { brand: "Mchose", model: "A7 V3 Ultra+", status: "likely", pids: [0x4033, 0x1014, 0x1018] },
  { brand: "Mchose", model: "A7 V3 Pro+", status: "likely", pids: [0x4032] },
  { brand: "Mchose", model: "A7 V3 Pro", status: "likely", pids: [0x4031] },
  { brand: "Mchose", model: "A7 V3", status: "likely", pids: [0x4030] },
  { brand: "Mchose", model: "A5 Pro Max", status: "supported", pids: [0xf019, 0xf013, 0xf015] },
  { brand: "Mchose", model: "K7 Ultra", status: "unknown" },
  { brand: "Mchose", model: "L7 Ultra+", status: "unknown" },
  { brand: "G-Wolves", model: "HTX Mini 8K", status: "unknown" },
  { brand: "Angry Miao", model: "Infinity .97", status: "unknown" },
  { brand: "Dark Project", model: "Novus SE", status: "unknown" },
  { brand: "Scyrox", model: "V8", status: "unknown" },
  { brand: "Mchose", model: "AX5", status: "unknown" },
  { brand: "AJAZZ", model: "AJ139 Pro", status: "unknown" },
  { brand: "AJAZZ", model: "AJ199", status: "unknown" },
  { brand: "Gravastar", model: "Mercury X Pro", status: "unknown" },
  { brand: "Gravastar", model: "M1", status: "unknown" },
  { brand: "Gravastar", model: "M2", status: "unknown" },
  { brand: "G-Wolves", model: "HT-M-H ACE Wireless", status: "unknown" },
  { brand: "Angry Miao", model: "Infinity Mouse", status: "unknown" },
  { brand: "VortexSeries", model: "IGNIX F3", status: "unknown" },
  { brand: "Darmoshark", model: "M3S", status: "unknown" },
  { brand: "Swiftpoint", model: "Z2", status: "unknown" },
  { brand: "Swiftpoint", model: "Z3", status: "unknown" },
  { brand: "Kreo", model: "Chimera V2 Wireless", status: "unknown" },
  { brand: "Kreo", model: "Harpy", status: "unknown" },
  { brand: "ipi", model: "Float 3950", status: "unknown" },
  { brand: "Solakaka", model: "SM802 Pro", status: "unknown" },
  { brand: "E-YOOSO", model: "X-44 Lite", status: "unknown" },
  { brand: "HAVIT", model: "Gamenote", status: "unknown" },
  { brand: "Empire Gaming", model: "RF906 Wireless", status: "unknown" },
  { brand: "DeadSkull", model: "Orbit Wired", status: "unknown" },
  { brand: "ISY", model: "IGM-6000", status: "unknown" },
  { brand: "2E Gaming", model: "MG355 WL", status: "pending" },
  { brand: "Acer", model: "OMW950", status: "pending" },
  { brand: "Acer", model: "Predator Cestus 353", status: "pending" },
  { brand: "Acer", model: "Easy Fit", status: "pending" },
  { brand: "Acer", model: "Nitro", status: "pending" },
  { brand: "Acer", model: "Wireless Optical", status: "pending" },
  { brand: "AJAZZ", model: "AJ139 V2 MC", status: "pending" },
  { brand: "AJAZZ", model: "AJ159 Pro", status: "pending" },
  { brand: "AJAZZ", model: "AJ179 Pro", status: "pending" },
  { brand: "AJAZZ", model: "AJ159P MC", status: "pending" },
  { brand: "AJAZZ", model: "AM3 Max", status: "pending" },
  { brand: "AJAZZ", model: "NJ08", status: "pending" },
  { brand: "AJAZZ", model: "AJ159 V2 MC", status: "pending" },
  { brand: "AJAZZ", model: "NJ07", status: "pending" },
  { brand: "Alienware", model: "AW610M", status: "pending" },
  { brand: "Amkette", model: "XS Series Flow Plus", status: "pending" },
  { brand: "Andowl", model: "Q-144", status: "pending" },
  { brand: "Ant Esports", model: "GM320", status: "pending" },
  { brand: "Ant Esports", model: "GM40", status: "pending" },
  { brand: "AQIRYS", model: "NYX", status: "pending" },
  { brand: "Arbiter Studio", model: "Akitsu Carbon Fiber 8K", status: "pending" },
  { brand: "Armaggeddon", model: "Textron Scorpion 7", status: "pending" },
  { brand: "Asus", model: "ROG Harpe Ace Mini", status: "pending" },
  { brand: "Asus", model: "P513", status: "pending" },
  { brand: "Asus", model: "P709", status: "pending" },
  { brand: "Asus", model: "ROG Harpe II Ace", status: "pending" },
  { brand: "Asus", model: "ROG Keris Wireless AimPoint", status: "pending" },
  { brand: "ATK", model: "A9", status: "pending" },
  { brand: "ATK", model: "A9 Ultimate+", status: "pending" },
  { brand: "ATK", model: "G3 Pro", status: "pending" },
  { brand: "ATK", model: "Blazing Sky X1 Pro", status: "pending" },
  { brand: "ATK", model: "Ghost", status: "pending" },
  { brand: "ATK", model: "VXE Mad R Major+", status: "pending" },
  { brand: "ATK", model: "X3", status: "pending" },
  { brand: "ATK", model: "X1", status: "pending" },
  { brand: "Attack Shark", model: "X3 Max", status: "pending" },
  { brand: "Attack Shark", model: "G3 Pro", status: "pending" },
  { brand: "Attack Shark", model: "V6", status: "pending" },
  { brand: "Attack Shark", model: "X11 Ultra", status: "pending" },
  { brand: "Attack Shark", model: "R11 Ultra", status: "pending" },
  { brand: "Attack Shark", model: "V3", status: "pending" },
  { brand: "Attack Shark", model: "X2", status: "pending" },
  { brand: "Attack Shark", model: "X5", status: "pending" },
  { brand: "Aula", model: "SC900 Pro", status: "pending" },
  { brand: "Aula", model: "SC620", status: "pending" },
  { brand: "Aula", model: "SC380 Pro", status: "pending" },
  { brand: "Aula", model: "SC680", status: "pending" },
  { brand: "Baracuda", model: "BGM-121", status: "pending" },
  { brand: "Battletron", model: "3218230", status: "pending" },
  { brand: "Bloody", model: "A70", status: "pending" },
  { brand: "Bloody", model: "ES7", status: "pending" },
  { brand: "Bloody", model: "P90 Pro", status: "pending" },
  { brand: "Bloody", model: "X5MAX", status: "pending" },
  { brand: "Bloody", model: "J90S", status: "pending" },
  { brand: "Cepter", model: "Falco", status: "pending" },
  { brand: "Cepter", model: "Falco Pro", status: "pending" },
  { brand: "Cooler Master", model: "MM310 (SF6 Chun-Li)", status: "pending" },
  { brand: "Cooler Master", model: "MM730", status: "pending" },
  { brand: "Corsair", model: "Harpoon RGB Wireless", status: "pending" },
  { brand: "Corsair", model: "Sabre RGB Pro Champion Series", status: "pending" },
  { brand: "Cosmic Byte", model: "Firestorm", status: "pending" },
  { brand: "Cosmic Byte", model: "Kilonova 3389IC", status: "pending" },
  { brand: "Cosmic Byte", model: "Raptor", status: "pending" },
  { brand: "CyberPower", model: "MO-131-302", status: "pending" },
  { brand: "Dareu", model: "EM901", status: "pending" },
  { brand: "Dark Project", model: "Nexus", status: "pending" },
  { brand: "Dark Project", model: "Novus Pro", status: "pending" },
  { brand: "DarkFlash", model: "DFM80", status: "pending" },
  { brand: "Darmoshark", model: "M3", status: "pending" },
  { brand: "Darmoshark", model: "M3 4K", status: "pending" },
  { brand: "Darmoshark", model: "M3 Pro", status: "pending" },
  { brand: "Darmoshark", model: "M5 V2", status: "pending" },
  { brand: "Dell", model: "MS116", status: "pending" },
  { brand: "Dell", model: "MS900", status: "pending" },
  { brand: "Delux", model: "M900 Pro", status: "pending" },
  { brand: "Delux", model: "M700 Ultra", status: "pending" },
  { brand: "Delux", model: "Seeker M618XSD", status: "pending" },
  { brand: "Delux", model: "M900 Mini", status: "pending" },
  { brand: "DEVO", model: "Solis Black", status: "pending" },
  { brand: "DEXP", model: "DGSAdept 66662", status: "pending" },
  { brand: "Drakar", model: "Asgard", status: "pending" },
  { brand: "Dune Voyager", model: "DV-GE4", status: "pending" },
  { brand: "Endgame Gear", model: "OP1 8K V2", status: "pending" },
  { brand: "Endgame Gear", model: "OP1w 4K", status: "pending" },
  { brand: "Endgame Gear", model: "XM1r", status: "pending" },
  { brand: "Endgame Gear", model: "XM2w 4K V2", status: "pending" },
  { brand: "Endgame Gear", model: "OP1 RGB", status: "pending" },
  { brand: "Endorfy", model: "EY6A016", status: "pending" },
  { brand: "Epomaker", model: "NEX Lite", status: "pending" },
  { brand: "Epomaker", model: "Carbon X", status: "pending" },
  { brand: "EVGA", model: "X12", status: "pending" },
  { brand: "Evofox", model: "Shadow X Pro", status: "pending" },
  { brand: "Evofox", model: "Banshee 3", status: "pending" },
  { brand: "Evofox", model: "Banshee", status: "pending" },
  { brand: "Evofox", model: "Blaze", status: "pending" },
  { brand: "EWEADN", model: "S9 Ultra", status: "pending" },
  { brand: "EWEADN", model: "GS01", status: "pending" },
  { brand: "EWEADN", model: "L1", status: "pending" },
  { brand: "EWEADN", model: "S9 Pro", status: "pending" },
  { brand: "Fantech", model: "Crypto II VX7V2", status: "pending" },
  { brand: "Fantech", model: "X9 Thor", status: "pending" },
  { brand: "Fantech", model: "Phantom II VX6", status: "pending" },
  { brand: "Fantech", model: "Venom I WGC", status: "pending" },
  { brand: "Fantech", model: "Venom II WGC2", status: "pending" },
  { brand: "Fantech", model: "Zeus X5s", status: "pending" },
  { brand: "Finalmouse", model: "Starlight Pro Tenz", status: "pending" },
  { brand: "Finalmouse", model: "UltraX", status: "pending" },
  { brand: "Fnatic", model: "Bolt", status: "pending" },
  { brand: "Furycube", model: "G13 Pro", status: "pending" },
  { brand: "G-Wolves", model: "Lycan 8K", status: "pending" },
  { brand: "G-Wolves", model: "WARG", status: "pending" },
  { brand: "G-Wolves", model: "Fenrir Asym", status: "pending" },
  { brand: "Gamen", model: "GM1200", status: "pending" },
  { brand: "Garuda Gear", model: "Hawk 1", status: "pending" },
  { brand: "Genesis", model: "Krypton 555", status: "pending" },
  { brand: "Genesis", model: "Krypton 750", status: "pending" },
  { brand: "Genesis", model: "Zircon XIII", status: "pending" },
  { brand: "Genesis", model: "Krypton 290", status: "pending" },
  { brand: "Gigabyte", model: "Aorus M5", status: "pending" },
  { brand: "Gigabyte", model: "Aorus M6", status: "pending" },
  { brand: "Glorious", model: "Model D 2 Wireless", status: "pending" },
  { brand: "Glorious", model: "Model D-", status: "pending" },
  { brand: "Hator", model: "Pulsar 3 Ultra 4K Wireless", status: "pending" },
  { brand: "HAVIT", model: "MS1035", status: "pending" },
  { brand: "HAVIT", model: "MS974WB", status: "pending" },
  { brand: "HAVIT", model: "MS966", status: "pending" },
  { brand: "HXSJ", model: "J900", status: "pending" },
  { brand: "HXSJ", model: "A869", status: "pending" },
  { brand: "HyperX", model: "HXMS235", status: "pending" },
  { brand: "HyperX", model: "Pulsefire Haste 2 Mini Wireless", status: "pending" },
  { brand: "HyperX", model: "HXMS231", status: "pending" },
  { brand: "Incott", model: "HPC02 Pro", status: "pending" },
  { brand: "INPHIC", model: "IN9 Pro", status: "pending" },
  { brand: "INPHIC", model: "09 Tri-Mode Wireless", status: "pending" },
  { brand: "INPHIC", model: "A9 Explorer V2", status: "pending" },
  { brand: "INPHIC", model: "F9", status: "pending" },
  { brand: "INPHIC", model: "F9-MECHA", status: "pending" },
  { brand: "ipi", model: "Float 88", status: "pending" },
  { brand: "ipi", model: "QI Pro", status: "pending" },
  { brand: "ipi", model: "Fly", status: "pending" },
  { brand: "ISY", model: "IWM 1000", status: "pending" },
  { brand: "JLab", model: "GO", status: "pending" },
  { brand: "KeepOut", model: "X9 Pro", status: "pending" },
  { brand: "Kensington", model: "Expert Wireless", status: "pending" },
  { brand: "Kensington", model: "Orbit Trackball With Scroll Ring", status: "pending" },
  { brand: "Keychron", model: "M7 8K", status: "pending" },
  { brand: "Kreo", model: "Hawk", status: "pending" },
  { brand: "Kreo", model: "Ikarus", status: "pending" },
  { brand: "Kreo", model: "Chimera V1", status: "pending" },
  { brand: "Kreo", model: "Pegasus", status: "pending" },
  { brand: "Krux", model: "KRX0115", status: "pending" },
  { brand: "Kysona", model: "Mercury Pro", status: "pending" },
  { brand: "Kysona", model: "Aztec", status: "pending" },
  { brand: "Kysona", model: "M600 V2", status: "pending" },
  { brand: "Lamzu", model: "Maya", status: "pending" },
  { brand: "Lamzu", model: "Maya Champion Edition", status: "pending" },
  { brand: "Lamzu", model: "Thorn V2", status: "pending" },
  { brand: "Lenovo", model: "IdeaPad Gaming M100", status: "pending" },
  { brand: "Lenovo", model: "Legion M410", status: "pending" },
  { brand: "Lenovo", model: "Legion M600", status: "pending" },
  { brand: "Lenovo", model: "Legion M600s", status: "pending" },
  { brand: "Logitech", model: "MX Master 3", status: "pending" },
  { brand: "Logitech", model: "G Pro X2 Superstrike", status: "pending" },
  { brand: "Logitech", model: "M510", status: "pending" },
  { brand: "Logitech", model: "Signature M650 / M650 L", status: "pending" },
  { brand: "Logitech", model: "MR0083", status: "pending" },
  { brand: "Logitech", model: "Pebble M350s", status: "pending" },
  { brand: "Logitech", model: "G302 Daedalus Prime", status: "pending" },
  { brand: "Logitech", model: "M90", status: "pending" },
  { brand: "Logitech", model: "G602", status: "pending" },
  { brand: "Logitech", model: "Lift Vertical", status: "pending" },
  { brand: "Logitech", model: "Ergo M575S", status: "pending" },
  { brand: "Logitech", model: "G700", status: "pending" },
  { brand: "Logitech", model: "G900", status: "pending" },
  { brand: "Logitech", model: "M-R0057", status: "pending" },
  { brand: "Logitech", model: "M170", status: "pending" },
  { brand: "Logitech", model: "M220", status: "pending" },
  { brand: "Logitech", model: "M330", status: "pending" },
  { brand: "Logitech", model: "M590", status: "pending" },
  { brand: "Logitech", model: "M705", status: "pending" },
  { brand: "Logitech", model: "M185", status: "pending" },
  { brand: "Logitech", model: "M190", status: "pending" },
  { brand: "Logitech", model: "M317", status: "pending" },
  { brand: "Logitech", model: "M550 L", status: "pending" },
  { brand: "Logitech", model: "MX Master", status: "pending" },
  { brand: "Mad Catz", model: "MMO TE", status: "pending" },
  { brand: "Mad Catz", model: "RAT 4+", status: "pending" },
  { brand: "Madlions", model: "MAD G+", status: "pending" },
  { brand: "Mambasnake", model: "M3", status: "pending" },
  { brand: "Mambasnake", model: "M2", status: "pending" },
  { brand: "Marvo", model: "G912W", status: "pending" },
  { brand: "Mchose", model: "A7X Ultra", status: "pending" },
  { brand: "Mchose", model: "G3 V2", status: "pending" },
  { brand: "Mchose", model: "G7", status: "pending" },
  { brand: "Mistel", model: "Md750 Delight", status: "pending" },
  { brand: "Mloong", model: "MX301", status: "pending" },
  { brand: "Mloong", model: "MX302", status: "pending" },
  { brand: "Monka", model: "M1 Pro", status: "pending" },
  { brand: "Monster Notebook", model: "Pusat One Shot Pro", status: "pending" },
  { brand: "MSI", model: "Clutch GM08", status: "pending" },
  { brand: "MSI", model: "Clutch GM41 Lightweight Wireless (Stalker 2 Edition)", status: "pending" },
  { brand: "MSI", model: "GM340", status: "pending" },
  { brand: "MSI", model: "Versa 300", status: "pending" },
  { brand: "Noir Gear", model: "S1 Series", status: "pending" },
  { brand: "NOS", model: "M750", status: "pending" },
  { brand: "NOS", model: "M800", status: "pending" },
  { brand: "Novotek", model: "MA-120", status: "pending" },
  { brand: "NYK", model: "Nemesis Neon MQ-32", status: "pending" },
  { brand: "NYK", model: "Nemesis Razor MQ-11", status: "pending" },
  { brand: "Onikuma", model: "CW917", status: "pending" },
  { brand: "Onikuma", model: "CW921", status: "pending" },
  { brand: "Onikuma", model: "DM02", status: "pending" },
  { brand: "Pichau", model: "Netuno Rainbow 01", status: "pending" },
  { brand: "Pictek", model: "T18", status: "pending" },
  { brand: "Pictek", model: "T7", status: "pending" },
  { brand: "Portronics", model: "Vader Max", status: "pending" },
  { brand: "Pulsar", model: "X2A V3", status: "pending" },
  { brand: "Pulsar", model: "X2 Mini", status: "pending" },
  { brand: "Pulsar", model: "X2 V2", status: "pending" },
  { brand: "Pulsar", model: "X2H V3 ES", status: "pending" },
  { brand: "Pulsar", model: "X3 CrazyLight", status: "pending" },
  { brand: "Pulsar", model: "X2N CrazyLight", status: "pending" },
  { brand: "Pwnage", model: "Symm 3", status: "pending" },
  { brand: "Rakk", model: "Dasig", status: "pending" },
  { brand: "Rakk", model: "Gahum", status: "pending" },
  { brand: "Rapoo", model: "VT9 Pro", status: "pending" },
  { brand: "Rapoo", model: "M1620", status: "pending" },
  { brand: "Rapoo", model: "MT760 Pro", status: "pending" },
  { brand: "Rapoo", model: "VT7 Air Max V2", status: "pending" },
  { brand: "Rapoo", model: "V25", status: "pending" },
  { brand: "Rapoo", model: "V25S", status: "pending" },
  { brand: "Rapoo", model: "VT200", status: "pending" },
  { brand: "Rapoo", model: "VT3", status: "pending" },
  { brand: "Rapoo", model: "VT7 Max", status: "pending" },
  { brand: "Raptor", model: "Storm Grip Wireless", status: "pending" },
  { brand: "Razer", model: "DeathAdder Essential (2021)", status: "pending" },
  { brand: "Razer", model: "RC30-030501", status: "pending" },
  { brand: "Razer", model: "RZ01-0385", status: "pending" },
  { brand: "Redgear", model: "A10", status: "pending" },
  { brand: "Redgear", model: "X12 V2", status: "pending" },
  { brand: "Redgear", model: "A20", status: "pending" },
  { brand: "Redgear", model: "F-15", status: "pending" },
  { brand: "Redragon", model: "M607", status: "pending" },
  { brand: "Redragon", model: "Phaser M609", status: "pending" },
  { brand: "Redragon", model: "M712-RGB", status: "pending" },
  { brand: "Redragon", model: "M811-RGB", status: "pending" },
  { brand: "Redragon", model: "M908", status: "pending" },
  { brand: "Redragon", model: "M916 Pro 1K", status: "pending" },
  { brand: "Redragon", model: "M919-ULT", status: "pending" },
  { brand: "Redragon", model: "M994", status: "pending" },
  { brand: "Redragon", model: "M998-ULT", status: "pending" },
  { brand: "Redragon", model: "M808-KS", status: "pending" },
  { brand: "RedThunder", model: "M10", status: "pending" },
  { brand: "Renew Force", model: "Viper Wireless BM-800", status: "pending" },
  { brand: "Rexus", model: "TP10", status: "pending" },
  { brand: "Rexus", model: "Daxa Air II Wired", status: "pending" },
  { brand: "Rexus", model: "DX-V1", status: "pending" },
  { brand: "Rexus", model: "RX-115", status: "pending" },
  { brand: "Rexus", model: "Clif II", status: "pending" },
  { brand: "Rexus", model: "Daxa Air Mini", status: "pending" },
  { brand: "Roccat", model: "Kone AIMO", status: "pending" },
  { brand: "Roccat", model: "XP", status: "pending" },
  { brand: "Rokytop", model: "TA1726492", status: "pending" },
  { brand: "Royal Kludge", model: "M3", status: "pending" },
  { brand: "Sades", model: "Kojin MX10", status: "pending" },
  { brand: "Sades", model: "Raiden Pro", status: "pending" },
  { brand: "Scyrox", model: "V6", status: "pending" },
  { brand: "Shenzhen", model: "DZK01", status: "pending" },
  { brand: "Skyshiu", model: "M3", status: "pending" },
  { brand: "Smailwolf", model: "M3+", status: "pending" },
  { brand: "Smailwolf", model: "M3 Pro+", status: "pending" },
  { brand: "Solakaka", model: "Sm600", status: "pending" },
  { brand: "Solakaka", model: "SM809 Pro", status: "pending" },
  { brand: "Solakaka", model: "E9 Pro", status: "pending" },
  { brand: "Solakaka", model: "SM822", status: "pending" },
  { brand: "Sprime", model: "PM1", status: "pending" },
  { brand: "SteelSeries", model: "Aerox 3 Wireless", status: "pending" },
  { brand: "SteelSeries", model: "Rival 5", status: "pending" },
  { brand: "SteelSeries", model: "Aerox 3 Wireless Gen 2", status: "pending" },
  { brand: "SteelSeries", model: "Aerox 5 Wireless", status: "pending" },
  { brand: "SteelSeries", model: "M-00029", status: "pending" },
  { brand: "SteelSeries", model: "Rival 600", status: "pending" },
  { brand: "T-Dagger", model: "T-TGM205", status: "pending" },
  { brand: "T-Wolf", model: "G590", status: "pending" },
  { brand: "T-Wolf", model: "Q13", status: "pending" },
  { brand: "T-Wolf", model: "X9", status: "pending" },
  { brand: "T-Wolf", model: "X3", status: "pending" },
  { brand: "Tecknet", model: "TK-MS009", status: "pending" },
  { brand: "Tecknet", model: "UM013", status: "pending" },
  { brand: "Tecware", model: "EX2", status: "pending" },
  { brand: "The G-Lab", model: "Kult 170", status: "pending" },
  { brand: "TIETI", model: "M01R", status: "pending" },
  { brand: "TRONIC", model: "HG06607E", status: "pending" },
  { brand: "Trust", model: "GXT 109 Felox", status: "pending" },
  { brand: "Trust", model: "GXT 111 Neebo", status: "pending" },
  { brand: "Trust", model: "21090", status: "pending" },
  { brand: "Trust", model: "GST 170", status: "pending" },
  { brand: "Trust", model: "GXT 144 Rexx", status: "pending" },
  { brand: "Turbo-X", model: "Erebus EM10", status: "pending" },
  { brand: "Unctrl", model: "M1", status: "pending" },
  { brand: "Urage", model: "Reaper 410", status: "pending" },
  { brand: "URX", model: "M1", status: "pending" },
  { brand: "UtechSmart", model: "Venus", status: "pending" },
  { brand: "UtechSmart", model: "Venus Pro Wireless", status: "pending" },
  { brand: "VGN", model: "F2 Pro Max", status: "pending" },
  { brand: "VGN", model: "Y2 Ultra", status: "pending" },
  { brand: "VGN", model: "F1 MOBA", status: "pending" },
  { brand: "VGUARD", model: "V6", status: "pending" },
  { brand: "VortexSeries", model: "Oni R1", status: "pending" },
  { brand: "VortexSeries", model: "Ignix F7", status: "pending" },
  { brand: "VortexSeries", model: "Ignix F5 Pro", status: "pending" },
  { brand: "VortexSeries", model: "Inno X3 Pro", status: "pending" },
  { brand: "Wraith", model: "W1", status: "pending" },
  { brand: "Xtrfy", model: "MZ1", status: "pending" },
  { brand: "Xtrfy", model: "M8", status: "pending" },
  { brand: "Yeah Magic", model: "Tyrfig V1", status: "pending" },
  { brand: "Zaopin", model: "Z1 Pro", status: "pending" },
  { brand: "Zaopin", model: "Z1 Pro Max", status: "pending" },
  { brand: "Zaopin", model: "Z2", status: "pending" },
  { brand: "Zebronics", model: "Transformer-M", status: "pending" },
  { brand: "Zowie", model: "ZA13-DW", status: "pending" },
  { brand: "Zowie", model: "EC1-CW", status: "pending" },
];
