// Supported-devices table, mirrored from the landing page.
//
// AUTO-GENERATED — do not edit by hand. Source of truth:
//   openmouse-landing-page/src/supported-mice.ts
// (the table behind openmouse.app/supported, re-checked against the
// @openmouse/protocol driver registry every time the landing page builds).
//
// Regenerate with:
//   node scripts/sync-supported-devices.mjs

export type SupportedDevicesStatus =
  | "supported"
  | "pr"
  | "quickwin"
  | "likely"
  | "driver"
  | "unknown"
  | "bridge"
  | "pending";

export interface SupportedDeviceEntry {
  brand: string;
  model: string;
  status: SupportedDevicesStatus;
  /** Known product ids from the page table (hex), when the driver pins them. */
  pids?: readonly number[];
}

export const SUPPORTED_DEVICES: readonly SupportedDeviceEntry[] = [
  { brand: "Logitech", model: "G502 (all variants)", status: "supported", pids: [0xc07d, 0xc08b] },
  { brand: "Logitech", model: "G203 LIGHTSYNC", status: "supported", pids: [0xc092] },
  { brand: "Logitech", model: "G203 PRODIGY", status: "supported", pids: [0xc084] },
  { brand: "Logitech", model: "G102 LIGHTSYNC", status: "supported", pids: [0xc089] },
  { brand: "Logitech", model: "G402 Hyperion Fury", status: "supported", pids: [0xc07e] },
  { brand: "Logitech", model: "G303 Daedalus Apex", status: "supported", pids: [0xc080] },
  { brand: "Logitech", model: "G303 Shroud Edition", status: "supported" },
  { brand: "Logitech", model: "G Pro (2017)", status: "supported", pids: [0xc085] },
  { brand: "Logitech", model: "G502 HERO (wired)", status: "supported", pids: [0xc08b] },
  { brand: "Logitech", model: "G Pro Hero", status: "supported", pids: [0xc08c] },
  { brand: "Logitech", model: "G903 HERO (wired)", status: "supported", pids: [0xc08e] },
  { brand: "Logitech", model: "G903 LIGHTSPEED", status: "supported" },
  { brand: "Logitech", model: "G403 HERO (wired)", status: "supported", pids: [0xc08f] },
  { brand: "Logitech", model: "G703 (wired)", status: "supported" },
  { brand: "Logitech", model: "G703 LIGHTSPEED", status: "supported" },
  { brand: "Logitech", model: "G Pro X Superlight", status: "supported", pids: [0xc094] },
  { brand: "Logitech", model: "PRO X SUPERLIGHT 2", status: "supported", pids: [0xc09b] },
  { brand: "Logitech", model: "PRO X SUPERLIGHT 2 SE", status: "supported" },
  { brand: "Logitech", model: "PRO X SUPERLIGHT 2 DEX", status: "supported", pids: [0xc0a0] },
  { brand: "Logitech", model: "G305", status: "supported" },
  { brand: "Logitech", model: "MX Master 3S", status: "supported", pids: [0xc548] },
  { brand: "Logitech", model: "G502 X (wired)", status: "supported", pids: [0xc099] },
  { brand: "Logitech", model: "G502 X PLUS (wireless)", status: "supported", pids: [0xc095] },
  { brand: "Logitech", model: "G502 X LIGHTSPEED", status: "supported", pids: [0xc098] },
  { brand: "Logitech", model: "MX Vertical", status: "driver" },
  { brand: "Logitech", model: "MX Master 4", status: "supported" },
  { brand: "Logitech", model: "MX Master 4S", status: "likely" },
  { brand: "Logitech", model: "G304", status: "supported" },
  { brand: "Logitech", model: "G Pro Wireless", status: "supported" },
  { brand: "Logitech", model: "G300s", status: "driver" },
  { brand: "Logitech", model: "G600", status: "driver" },
  { brand: "Logitech", model: "G Pro 2 Lightspeed", status: "supported", pids: [0xc09a] },
  { brand: "Logitech", model: "G502 Lightspeed", status: "supported" },
  { brand: "Logitech", model: "G604 LIGHTSPEED", status: "supported" },
  { brand: "Logitech", model: "MX Master 2S", status: "driver" },
  { brand: "Logitech", model: "MX Anywhere 3", status: "supported", pids: [0xc548] },
  { brand: "Logitech", model: "MX Anywhere 3S", status: "supported", pids: [0xc548] },
  { brand: "Logitech", model: "G309 Lightspeed", status: "supported" },
  { brand: "Logitech", model: "MX Ergo S", status: "supported", pids: [0xc548] },
  { brand: "Logitech", model: "MX Anywhere 2", status: "driver" },
  { brand: "Logitech", model: "Compact Wireless", status: "unknown" },
  { brand: "Logitech", model: "G700s", status: "driver" },
  { brand: "Logitech", model: "M171 Wireless", status: "driver" },
  { brand: "Roccat", model: "Kone Pro Air", status: "driver" },
  { brand: "Roccat", model: "Kone XP Air", status: "driver" },
  { brand: "Roccat", model: "Tyon", status: "driver" },
  { brand: "Roccat", model: "Nyth", status: "driver" },
  { brand: "Roccat", model: "Kain 100 AIMO", status: "driver" },
  { brand: "Roccat", model: "Kone Pro", status: "driver" },
  { brand: "Redragon", model: "M725 Honeycomb", status: "driver" },
  { brand: "Redragon", model: "Impact Elite M913", status: "driver" },
  { brand: "Redragon", model: "PREDATOR M612", status: "driver" },
  { brand: "Redragon", model: "K1ng M916 Pro 4K", status: "driver" },
  { brand: "Redragon", model: "M711 Cobra", status: "driver" },
  { brand: "Redragon", model: "M917 Pro", status: "driver" },
  { brand: "Redragon", model: "M991", status: "driver" },
  { brand: "Redragon", model: "M703", status: "driver" },
  { brand: "Redragon", model: "TAIPAN PRO M810", status: "driver" },
  { brand: "Redragon", model: "Ranger Lite", status: "driver" },
  { brand: "Redragon", model: "Infernal Dragon", status: "driver" },
  { brand: "Redragon", model: "M696 Pro", status: "driver" },
  { brand: "Redragon", model: "M721 Pro", status: "driver" },
  { brand: "Redragon", model: "M724 K1NG 1K", status: "supported", pids: [0xfc7a] },
  { brand: "Ryunix", model: "KYU Pro MX1", status: "supported", pids: [0x26e, 0x26f] },
  { brand: "Delux", model: "M800 Mini", status: "supported", pids: [0xfa60, 0xfa55] },
  { brand: "Dareu", model: "A950 PRO Mg", status: "supported", pids: [0x1114, 0x1117] },
  { brand: "Attack Shark", model: "X3", status: "bridge" },
  { brand: "Attack Shark", model: "X11", status: "bridge" },
  { brand: "Attack Shark", model: "R5 Ultra", status: "supported", pids: [0x46, 0x47] },
  { brand: "Attack Shark", model: "X6", status: "bridge" },
  { brand: "Attack Shark", model: "R3", status: "likely", pids: [0x402d, 0x4026] },
  { brand: "Attack Shark", model: "R1", status: "bridge" },
  { brand: "Attack Shark", model: "X8 Ultra", status: "bridge" },
  { brand: "Attack Shark", model: "X8 SE", status: "bridge" },
  { brand: "Attack Shark", model: "X1", status: "bridge" },
  { brand: "Attack Shark", model: "V3 Pro", status: "bridge" },
  { brand: "Attack Shark", model: "X3 Pro", status: "bridge" },
  { brand: "Attack Shark", model: "X11 SE", status: "bridge" },
  { brand: "Attack Shark", model: "X8 PLUS", status: "bridge" },
  { brand: "Attack Shark", model: "X12", status: "bridge" },
  { brand: "Attack Shark", model: "R6", status: "bridge" },
  { brand: "Attack Shark", model: "G3", status: "bridge" },
  { brand: "Attack Shark", model: "R2", status: "supported", pids: [0x402d, 0x4026] },
  { brand: "Lingbao", model: "M5 Pro", status: "supported", pids: [0x402d, 0x4026] },
  { brand: "Razer", model: "DeathAdder V3 (wired)", status: "supported" },
  { brand: "Razer", model: "DeathAdder V2 (wired)", status: "supported", pids: [0x84] },
  { brand: "Razer", model: "DeathAdder V2 Pro", status: "supported", pids: [0x7c, 0x7d] },
  { brand: "Razer", model: "Cobra", status: "supported", pids: [0xa3] },
  { brand: "Razer", model: "Viper V3 Pro", status: "supported", pids: [0xc0, 0xc1] },
  { brand: "Razer", model: "Viper V2 Pro", status: "supported", pids: [0xa5, 0xa6] },
  { brand: "Razer", model: "Viper V2 Pro (HyperPolling 8000 Hz)", status: "likely", pids: [0xb3] },
  { brand: "Razer", model: "DeathAdder Essential", status: "supported", pids: [0x6e, 0x71, 0x98] },
  { brand: "Razer", model: "Viper Mini", status: "supported", pids: [0x8a] },
  { brand: "Razer", model: "Viper V3 HyperSpeed", status: "supported", pids: [0xb8] },
  { brand: "Razer", model: "Viper V4 Pro", status: "supported", pids: [0xe5, 0xe6] },
  { brand: "Razer", model: "Basilisk V3 (wired)", status: "likely" },
  { brand: "Razer", model: "Basilisk V3 Pro", status: "likely" },
  { brand: "Razer", model: "Viper Ultimate", status: "likely" },
  { brand: "Razer", model: "Basilisk V3 X HyperSpeed", status: "likely", pids: [0xb9] },
  { brand: "Razer", model: "DeathAdder V2 X HyperSpeed", status: "likely" },
  { brand: "Razer", model: "Viper 8KHz", status: "likely" },
  { brand: "Razer", model: "Naga V2 Pro", status: "likely" },
  { brand: "Razer", model: "DeathAdder V3 Pro", status: "supported", pids: [0xb6, 0xb7] },
  { brand: "Razer", model: "DeathAdder V4 Pro", status: "supported", pids: [0xbe, 0xbf] },
  { brand: "Razer", model: "DeathAdder V4 Pro Carbon Fiber Edition", status: "supported", pids: [0xef, 0xf0] },
  { brand: "Razer", model: "Naga Trinity", status: "likely" },
  { brand: "Razer", model: "Naga X", status: "likely" },
  { brand: "Razer", model: "Basilisk Essential", status: "likely" },
  { brand: "Razer", model: "Basilisk", status: "likely" },
  { brand: "Razer", model: "Orochi V2", status: "likely" },
  { brand: "Razer", model: "Cobra Pro", status: "likely", pids: [0xaf, 0xb0] },
  { brand: "Razer", model: "Viper V3 Pro SE", status: "likely", pids: [0xde, 0xdf] },
  { brand: "Razer", model: "Basilisk X HyperSpeed", status: "likely" },
  { brand: "Razer", model: "Naga V2 HyperSpeed", status: "likely" },
  { brand: "Razer", model: "Basilisk Ultimate", status: "likely" },
  { brand: "Razer", model: "DeathAdder Elite", status: "likely", pids: [0x5c] },
  { brand: "Razer", model: "Abyssus 1800", status: "likely", pids: [0x20] },
  { brand: "Razer", model: "Abyssus 2000", status: "likely", pids: [0x5e] },
  { brand: "Razer", model: "Abyssus 2014", status: "likely", pids: [0x42] },
  { brand: "Razer", model: "Abyssus Elite (D.Va Edition)", status: "likely", pids: [0x6a] },
  { brand: "Razer", model: "Abyssus Essential", status: "likely", pids: [0x6b] },
  { brand: "Razer", model: "Abyssus V2", status: "likely", pids: [0x5b] },
  { brand: "Razer", model: "Atheris", status: "likely", pids: [0x62] },
  { brand: "Razer", model: "Basilisk Mobile", status: "likely", pids: [0xd3, 0xd4] },
  { brand: "Razer", model: "Basilisk V2", status: "likely", pids: [0x85] },
  { brand: "Razer", model: "Basilisk V3 35K", status: "likely", pids: [0xcb] },
  { brand: "Razer", model: "Basilisk V3 Pro 35K", status: "likely", pids: [0xcc, 0xcd] },
  { brand: "Razer", model: "Basilisk V3 Pro 35K Phantom Green", status: "likely", pids: [0xd6, 0xd7] },
  { brand: "Razer", model: "DeathAdder 1800", status: "likely", pids: [0x38] },
  { brand: "Razer", model: "DeathAdder 2000", status: "likely", pids: [0x4f] },
  { brand: "Razer", model: "DeathAdder 2013", status: "likely", pids: [0x37] },
  { brand: "Razer", model: "DeathAdder 3500", status: "likely", pids: [0x54] },
  { brand: "Razer", model: "DeathAdder Chroma", status: "likely", pids: [0x43] },
  { brand: "Razer", model: "DeathAdder V2 Lite", status: "likely", pids: [0xa1] },
  { brand: "Razer", model: "DeathAdder V2 Mini", status: "likely", pids: [0x8c] },
  { brand: "Razer", model: "DeathAdder V3 HyperSpeed", status: "likely", pids: [0xc4, 0xc5] },
  { brand: "Razer", model: "Diamondback Chroma", status: "likely", pids: [0x4c] },
  { brand: "Razer", model: "Imperator 2012", status: "likely", pids: [0x2f] },
  { brand: "Razer", model: "Lancehead", status: "likely", pids: [0x59, 0x5a] },
  { brand: "Razer", model: "Lancehead Tournament Edition", status: "likely", pids: [0x60] },
  { brand: "Razer", model: "Lancehead Wireless", status: "likely", pids: [0x6f, 0x70] },
  { brand: "Razer", model: "Mamba", status: "likely", pids: [0x44, 0x45] },
  { brand: "Razer", model: "Mamba 2012", status: "likely", pids: [0x24, 0x25] },
  { brand: "Razer", model: "Mamba Elite", status: "likely", pids: [0x6c] },
  { brand: "Razer", model: "Mamba Tournament Edition", status: "likely", pids: [0x46] },
  { brand: "Razer", model: "Mamba Wireless", status: "likely", pids: [0x72, 0x73] },
  { brand: "Razer", model: "Naga", status: "likely", pids: [0x15] },
  { brand: "Razer", model: "Naga 2012", status: "likely", pids: [0x2e] },
  { brand: "Razer", model: "Naga 2014", status: "likely", pids: [0x40] },
  { brand: "Razer", model: "Naga Chroma", status: "likely", pids: [0x53] },
  { brand: "Razer", model: "Naga Epic", status: "likely", pids: [0x1f] },
  { brand: "Razer", model: "Naga Epic Chroma", status: "likely", pids: [0x3e, 0x3f] },
  { brand: "Razer", model: "Naga Hex", status: "likely", pids: [0x41] },
  { brand: "Razer", model: "Naga Hex (Red)", status: "likely", pids: [0x36] },
  { brand: "Razer", model: "Naga Hex V2", status: "likely", pids: [0x50] },
  { brand: "Razer", model: "Naga Left-Handed Edition 2020", status: "likely", pids: [0x8d] },
  { brand: "Razer", model: "Naga Pro", status: "likely", pids: [0x8f, 0x90] },
  { brand: "Razer", model: "Orochi", status: "likely", pids: [0x48] },
  { brand: "Razer", model: "Orochi 2013", status: "likely", pids: [0x39] },
  { brand: "Razer", model: "Ouroboros 2012", status: "likely", pids: [0x32] },
  { brand: "Razer", model: "Pro Click", status: "likely", pids: [0x77, 0x80] },
  { brand: "Razer", model: "Pro Click Mini", status: "likely", pids: [0x9a] },
  { brand: "Razer", model: "Pro Click V2", status: "likely", pids: [0xd0, 0xd1] },
  { brand: "Razer", model: "Pro Click V2 Vertical Edition", status: "likely", pids: [0xc7, 0xc8] },
  { brand: "Razer", model: "Taipan", status: "likely", pids: [0x34] },
  { brand: "Razer", model: "Viper Mini Signature Edition", status: "likely", pids: [0x9e, 0x9f] },
  { brand: "HyperX", model: "Pulsefire Haste", status: "likely", pids: [0x1727, 0xf8f, 0x48e, 0x28e] },
  { brand: "HyperX", model: "Pulsefire Haste 2", status: "driver" },
  { brand: "HyperX", model: "Pulsefire Haste 2 Wireless", status: "driver" },
  { brand: "HyperX", model: "Pulsefire FPS Pro", status: "driver" },
  { brand: "HyperX", model: "Pulsefire Fuse", status: "driver" },
  { brand: "SteelSeries", model: "Aerox 9 Wireless", status: "supported", pids: [0x185a, 0x1876, 0x1858, 0x1874] },
  { brand: "SteelSeries", model: "Sensei Ten", status: "supported", pids: [0x1832, 0x1834] },
  { brand: "SteelSeries", model: "Aerox 5", status: "supported", pids: [0x1850, 0x1854, 0x185e, 0x1862, 0x1852, 0x185c, 0x1860] },
  { brand: "SteelSeries", model: "Rival 3 Wireless", status: "supported", pids: [0x1830] },
  { brand: "SteelSeries", model: "Rival 3 (wired)", status: "supported", pids: [0x1824, 0x184c] },
  { brand: "SteelSeries", model: "Rival 650 Wireless", status: "supported", pids: [0x172b, 0x1726] },
  { brand: "SteelSeries", model: "Aerox 3", status: "supported", pids: [0x1836] },
  { brand: "SteelSeries", model: "Prime+", status: "supported", pids: [0x182c] },
  { brand: "SteelSeries", model: "Rival 310", status: "supported", pids: [0x1720, 0x171e, 0x1736] },
  { brand: "SteelSeries", model: "Prime Mini Wireless", status: "supported", pids: [0x184a, 0x1848] },
  { brand: "Corsair", model: "NIGHTSWORD RGB", status: "supported", pids: [0x1b5c] },
  { brand: "Corsair", model: "Harpoon RGB Pro", status: "driver" },
  { brand: "Corsair", model: "Katar Pro", status: "driver" },
  { brand: "Corsair", model: "M65 Pro RGB", status: "driver" },
  { brand: "Corsair", model: "Sabre V2 Pro Ultralight", status: "driver" },
  { brand: "Corsair", model: "Scimitar Elite Wireless SE", status: "driver" },
  { brand: "Corsair", model: "M65 RGB Elite", status: "driver" },
  { brand: "Corsair", model: "Scimitar RGB Elite", status: "driver" },
  { brand: "Corsair", model: "Ironclaw RGB", status: "driver" },
  { brand: "Glorious", model: "Model O 2 Pro Wireless", status: "supported", pids: [0x2033] },
  { brand: "Glorious", model: "Model O", status: "supported", pids: [0x2011, 0x2022] },
  { brand: "Glorious", model: "Model D Wireless", status: "supported", pids: [0x2012, 0x2023] },
  { brand: "Glorious", model: "Model D", status: "supported", pids: [0x2012] },
  { brand: "Glorious", model: "Model O2 Pro 4K/8K", status: "likely", pids: [0x201b, 0x2035] },
  { brand: "Glorious", model: "Model O Pro", status: "supported", pids: [0x2015, 0x2027] },
  { brand: "Glorious", model: "Model D2 Pro Wireless 8K", status: "likely", pids: [0x201c, 0x2036] },
  { brand: "Glorious", model: "Model O3 Wireless", status: "likely", pids: [0xa312, 0xa300] },
  { brand: "Endgame Gear", model: "XM2w 4K", status: "supported" },
  { brand: "Endgame Gear", model: "OP1we", status: "supported", pids: [0x1961, 0x1962] },
  { brand: "Endgame Gear", model: "OP1w 4K v2", status: "likely" },
  { brand: "Endgame Gear", model: "OP1 8K", status: "supported", pids: [0x1964, 0x1976, 0x1978] },
  { brand: "Endgame Gear", model: "XM2 8K", status: "supported", pids: [0x1966, 0x1980] },
  { brand: "ATK", model: "F1 V2 Ultra Max", status: "supported" },
  { brand: "ATK", model: "VXE Dragonfly R1 Pro", status: "likely" },
  { brand: "VXE", model: "R1 Pro Max", status: "supported", pids: [0xf58a, 0xf58c] },
  { brand: "VXE", model: "R1 (SE)", status: "likely" },
  { brand: "VXE", model: "R1 SE+", status: "supported", pids: [0xf58e, 0xf58f] },
  { brand: "ATK", model: "X1 V2 Ultimate", status: "likely" },
  { brand: "ATK", model: "A9 Air", status: "likely" },
  { brand: "ATK", model: "F1 Ultimate", status: "likely" },
  { brand: "ATK", model: "F1 Ultimate 2.0", status: "likely" },
  { brand: "ATK", model: "A9 Mini +", status: "likely" },
  { brand: "ATK", model: "VXE Mad R Major", status: "likely" },
  { brand: "ATK", model: "ZERO", status: "supported", pids: [0x1154, 0x1155] },
  { brand: "ATK", model: "VXE Zero Normal", status: "likely" },
  { brand: "VGN", model: "Dragonfly F2 Master+", status: "supported", pids: [0xfb56, 0xfb57] },
  { brand: "WLMouse", model: "Beast X", status: "supported", pids: [0xa883, 0xa884] },
  { brand: "WLMouse", model: "Beast Mini", status: "supported", pids: [0xa885, 0xa886] },
  { brand: "WLMouse", model: "Beast X Pro", status: "supported", pids: [0xa870, 0xa871] },
  { brand: "WLMouse", model: "Sword X", status: "supported", pids: [0xa878, 0xa879] },
  { brand: "WLMouse", model: "Beast Max", status: "supported", pids: [0xa880, 0xa881] },
  { brand: "Pulsar", model: "Tenz Signature", status: "supported" },
  { brand: "Pulsar", model: "X2h", status: "supported" },
  { brand: "Pulsar", model: "X2 V3 ES Mini", status: "supported" },
  { brand: "Pulsar", model: "X3 Medium", status: "supported", pids: [0x3409, 0x3410, 0x5402, 0x5403] },
  { brand: "Pulsar", model: "X2F", status: "supported" },
  { brand: "VAXEE", model: "XE Wireless", status: "supported", pids: [0x1003] },
  { brand: "VAXEE", model: "NP-01S Wireless", status: "supported", pids: [0x1004] },
  { brand: "VAXEE", model: "AX Wireless", status: "supported", pids: [0x1005] },
  { brand: "VAXEE", model: "NP-01 Wireless", status: "supported", pids: [0x1006] },
  { brand: "VAXEE", model: "XE-S Wireless", status: "supported", pids: [0x1007] },
  { brand: "VAXEE", model: "XE-S-L Wireless", status: "supported", pids: [0x1008] },
  { brand: "VAXEE", model: "VAXEE x Ninjutso Sora", status: "supported", pids: [0x1009] },
  { brand: "VAXEE", model: "E1 Wireless", status: "supported", pids: [0x1010] },
  { brand: "VAXEE", model: "NP-01S V2 Wireless", status: "supported", pids: [0x1011] },
  { brand: "VAXEE", model: "XE V2 Wireless", status: "supported", pids: [0x1012] },
  { brand: "VAXEE", model: "NP-01S Ergo Wireless", status: "supported", pids: [0x1013] },
  { brand: "VAXEE", model: "NP-01S V3 Wireless", status: "supported", pids: [0x1014] },
  { brand: "VAXEE", model: "NP-01 Ergo Wireless", status: "supported", pids: [0x1015] },
  { brand: "Lamzu", model: "Maya X", status: "supported", pids: [0x1c, 0x1d, 0x1e] },
  { brand: "Lamzu", model: "Inca", status: "supported", pids: [0x9, 0xf, 0x10] },
  { brand: "Lamzu", model: "Atlantis (shared family ids)", status: "likely", pids: [0xf50f] },
  { brand: "Lamzu", model: "Thorn", status: "quickwin" },
  { brand: "CRDRAKO", model: "KO-ONE", status: "supported", pids: [0x6a, 0x6b] },
  { brand: "Ninjutso", model: "Sora V2", status: "supported", pids: [0xae11, 0xae12, 0xae13, 0xae14, 0xae15, 0xae16] },
  { brand: "Ninjutso", model: "Sora V3", status: "supported", pids: [0xe010] },
  { brand: "Ninjutso", model: "TEN", status: "supported", pids: [0xe020, 0xea01] },
  { brand: "Ninjutso", model: "Sora", status: "likely" },
  { brand: "Teevolution", model: "Terra Pro", status: "supported", pids: [0xf520, 0xf523, 0xf5bb, 0xf522] },
  { brand: "WALLHACK", model: "M-001", status: "supported", pids: [0x1110, 0x807] },
  { brand: "Finalmouse", model: "Starlight-12 / ULX", status: "supported", pids: [0x100] },
  { brand: "Zaunkoenig", model: "M3K", status: "supported", pids: [0xa462] },
  { brand: "Zaunkoenig", model: "M2K", status: "supported", pids: [0xa3cf] },
  { brand: "moddoMOUSE", model: "moddoMOUSE", status: "supported" },
  { brand: "Orbital", model: "Ghost / Pathfinder V2", status: "supported", pids: [0x80c] },
  { brand: "Microsoft", model: "Pro Intellimouse", status: "supported", pids: [0x82a] },
  { brand: "Microsoft", model: "Classic Intellimouse", status: "supported", pids: [0x823] },
  { brand: "Keychron", model: "Nape Pro", status: "supported", pids: [0x440] },
  { brand: "Keychron", model: "M6", status: "supported", pids: [0xd060, 0xd029] },
  { brand: "Asus", model: "Harpe Ace Aim Lab", status: "driver" },
  { brand: "Asus", model: "TUF Gaming M5", status: "driver" },
  { brand: "Asus", model: "Gladius II Core", status: "driver" },
  { brand: "Asus", model: "Strix Impact III", status: "driver" },
  { brand: "Asus", model: "TUF Gaming M3 Gen 1", status: "driver" },
  { brand: "Asus", model: "ROG Gladius II P502", status: "supported", pids: [0x1845] },
  { brand: "Incott", model: "G23 V2 (SE / Pro)", status: "supported", pids: [0x522c, 0x622c] },
  { brand: "Incott", model: "GHERO (and Pro)", status: "likely" },
  { brand: "Incott", model: "G23 (and Pro)", status: "likely" },
  { brand: "Incott", model: "G24 (and Pro)", status: "likely" },
  { brand: "Incott", model: "Zero 29 (and Pro)", status: "likely" },
  { brand: "Incott", model: "Zero 39 (and Pro)", status: "likely" },
  { brand: "RAWM", model: "Blade 1", status: "supported", pids: [0x2328] },
  { brand: "RAWM", model: "ML01", status: "supported", pids: [0x2329] },
  { brand: "RAWM", model: "MH01", status: "supported", pids: [0x232c] },
  { brand: "RAWM", model: "SL01", status: "supported", pids: [0x232d] },
  { brand: "RAWM", model: "SH01", status: "supported", pids: [0x232e, 0x232f] },
  { brand: "RAWM", model: "SH01 Pro", status: "supported", pids: [0x2330, 0x2332] },
  { brand: "RAWM", model: "MH01 Pro", status: "supported", pids: [0x2331] },
  { brand: "RAWM", model: "ES21", status: "supported", pids: [0x2333] },
  { brand: "RAWM", model: "ES21 Pro", status: "supported", pids: [0x2334] },
  { brand: "RAWM", model: "ES21M", status: "supported", pids: [0x2337] },
  { brand: "RAWM", model: "ER21 Pro", status: "supported", pids: [0x2338] },
  { brand: "RAWM", model: "ER21M", status: "supported", pids: [0x2339] },
  { brand: "Bloody", model: "Max W95", status: "driver" },
  { brand: "Fantech", model: "THOR II X16", status: "driver" },
  { brand: "Cooler Master", model: "MasterMouse MM720", status: "driver" },
  { brand: "Cooler Master", model: "MM711", status: "driver" },
  { brand: "K-snake", model: "X11", status: "supported", pids: [0x2255] },
  { brand: "Hitscan", model: "Hyperlight", status: "unknown" },
  { brand: "RAWM", model: "Leviathan V4", status: "unknown" },
  { brand: "AJAZZ", model: "AJ159 Apex", status: "unknown" },
  { brand: "Furycube", model: "G11", status: "unknown" },
  { brand: "Mchose", model: "A7 V2 Ultra+", status: "supported", pids: [0x4021, 0x100b] },
  { brand: "Mchose", model: "MagDock (charging base)", status: "supported", pids: [0x1012] },
  { brand: "Mchose", model: "A7 V2 Ultra", status: "likely" },
  { brand: "Mchose", model: "A7 V2 Pro+", status: "likely" },
  { brand: "Mchose", model: "A7 V2 Pro", status: "likely" },
  { brand: "Mchose", model: "A7 V3 Ultra+", status: "likely", pids: [0x4033, 0x1014, 0x1018] },
  { brand: "Mchose", model: "A7 V3 Pro+", status: "likely", pids: [0x4032] },
  { brand: "Mchose", model: "A7 V3 Pro", status: "likely", pids: [0x4031] },
  { brand: "Mchose", model: "A7 V3", status: "likely", pids: [0x4030] },
  { brand: "Mchose", model: "A5 Pro Max", status: "supported", pids: [0xf019, 0xf013, 0xf015] },
  { brand: "Mchose", model: "K7 Ultra", status: "unknown" },
  { brand: "Mchose", model: "L7 Ultra+", status: "unknown" },
  { brand: "G-Wolves", model: "HTX Mini 8K", status: "unknown" },
  { brand: "Angry Miao", model: "Infinity .97", status: "unknown" },
  { brand: "Dark Project", model: "Novus SE", status: "unknown" },
  { brand: "Scyrox", model: "V8", status: "unknown" },
  { brand: "Mchose", model: "AX5", status: "unknown" },
  { brand: "AJAZZ", model: "AJ139 Pro", status: "unknown" },
  { brand: "AJAZZ", model: "AJ199", status: "unknown" },
  { brand: "Gravastar", model: "Mercury X Pro", status: "unknown" },
  { brand: "Gravastar", model: "M1", status: "unknown" },
  { brand: "Gravastar", model: "M2", status: "unknown" },
  { brand: "G-Wolves", model: "HT-M-H ACE Wireless", status: "unknown" },
  { brand: "Angry Miao", model: "Infinity Mouse", status: "unknown" },
  { brand: "VortexSeries", model: "IGNIX F3", status: "unknown" },
  { brand: "Darmoshark", model: "M3S", status: "unknown" },
  { brand: "Swiftpoint", model: "Z2", status: "unknown" },
  { brand: "Swiftpoint", model: "Z3", status: "unknown" },
  { brand: "Kreo", model: "Chimera V2 Wireless", status: "unknown" },
  { brand: "Kreo", model: "Harpy", status: "unknown" },
  { brand: "ipi", model: "Float 3950", status: "unknown" },
  { brand: "Solakaka", model: "SM802 Pro", status: "unknown" },
  { brand: "E-YOOSO", model: "X-44 Lite", status: "unknown" },
  { brand: "HAVIT", model: "Gamenote", status: "unknown" },
  { brand: "Empire Gaming", model: "RF906 Wireless", status: "unknown" },
  { brand: "DeadSkull", model: "Orbit Wired", status: "unknown" },
  { brand: "ISY", model: "IGM-6000", status: "unknown" },
];
